---
- name: Deploying the PHP Application to Dev environment
  become: true
  hosts: todo

  tasks:
    - name: install remi and rhel repo
      yum:
        name: 
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
          - dnf-utils
          - http://rpms.remirepo.net/enterprise/remi-release-8.rpm
        disable_gpg_check: yes

    - name: Installl httpd on the webserver
      yum:
        name: httpd
        state: present
    
    - name: Ensure httpd is started and Enabled
      service:
        name: httpd
        state: started
        enabled: yes

    - name: install PHP
      yum:
        name:
          - php
          - php-mysqlnd
          - php-gd 
          - php-curl
          - unzip
          - php-common
          - php-mbstring
          - php-opcache
          - php-intl
          - php-xml
          - php-fpm
          - php-json
        enablerepo: php:remi-7.4
        state: present

    - name: Download the artifact
      get_url:
        url: http:http://34.245.98.204:8082/artifactory/PBL/php-todo
        dest: /home/ec2-user/
        url_username: admin
        url_password: Macaustin1990!

    - name: Unzip the artifacts
      unarchive:
        src: /home/ec2-user/php-todo
        dest: /home/ec2-user/
        remote_src: yes

    - name: deploy the code
      copy:
        src: /home/ec2-user/var/lib/jenkins/workspace/php-todo_main/
        dest: /var/www/html/
        force: yes
        remote_src: yes

    - name: remove Apache default page
      file:
        path: /etc/httpd/conf.d/welcome.conf
        state: absent

    - name: restart httpd
      service:
        name: httpd
        state: restarted