[jenkins]
172.31.39.197 ansible_ssh_user='ec2-user'

[nginx]
172.31.28.238 ansible_ssh_user='ec2-user'

[sonarqube]
172.31.46.16 ansible_ssh_user='ubuntu'

[artifactory]
172.31.6.201 ansible_ssh_user='ec2-user'