pipeline {
    agent any
// Set the parameters for the environments
    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }
// Configure Environment to locate ansicble.cfg file
    environment {
        ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }
// set the different stages of the pipeline
    stages {
        stage ('Initial cleanup') {
            steps{
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }

        }

        stage('Checkout SCM'){
            steps{
                git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/Mitchxxx/ansible-config.git'
            }
        }

        stage('Prepare Ansible for Execution') {
            steps {
                sh 'echo ${WORKSPACE}'
                sh "sed -i '3 a roles_path=${WORKSPACE}/roles' ${WORKSPACE}/deploy/ansible.cfg"
            }
        }

        stage('Run Ansible playbook'){
            steps{
                ansiblePlaybook become: true, colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}.yml', playbook: 'playbooks/site.yml'
            }
        }

        stage('Clean Up'){
            steps{
                    cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
            }
        }
    }
}