pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG="${WORSPACE}/deploy/ansible.cfg"
    }

    stages {
        stage ('Initial cleanup') {
            steps{
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }

        }

        stage('Checkout SCM'){
            steps{
                git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/Mitchxxx/ansible-config.git'
            }
        }

        stage('Prepare Ansible for Execution') {
            steps {
                sh 'echo ${WORKSPACE}'
                sh "sed -i '3 a ansible_roles_path=${WORKSPACE}/roles' ${WORKSPACE}/deploy/ansible.cfg"
                sh 'cat ${WORKSPACE}/deploy/ansible.cfg'
            }
        }

        stage('Run Ansible playbook'){
            steps{
                ansiblePlaybook become: true, colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev.yml', playbook: 'playbooks/site.yml'
            }
        }

        stage('Clean Up'){
            steps{
                    cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
            }
        }
    }
}