pipeline {
    agent any

    stages {
        stage('Build'){
            steps{
                script{
                    sh 'echo "Building stage"'
                }
            }
        }

        stage('Test'){
            steps {
                script {
                    sh 'echo "Testing stage"'
                }
            }
        }

        stage('Package'){
            steps {
                script {
                    sh 'echo "Packaging App"'
                }
            }
        }

        stage('Deploy'){
            steps {
                script {
                    sh 'echo "Deploying App"'
                }
            }
        }

        stage('Clean Up'){
            steps {
                script {
                    sh 'echo "Clean Up Stage"'
                }
            }
        }
    }
}