---
- name: update web, nfs and db servers
  hosts: webservers, nfs
  remote_user: ec2-user
  become: true
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

- name: update Lb and db servers
  hosts: db, lb
  remote_user: ubuntu
  become: true
  become_user: root
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest


- name: create directory, file and set timezone on all servers
  hosts: webservers, nfs, db, lb
  become: true
  tasks:
    - name: create a directory
      file:
        path: /home/sample
        state: directory
        mode: '0755'

    - name: create a new file
      file:
        path: /home/sample/ansible.txt
        state: touch
        mode: '0644'

    - name: set a new timezone to Africa
      timezone:
        name: America/Newyork