---
#- hosts: all
# - name: Include dynamic variables
#   import_playbook: ../static-assignments/common.yml
#   include: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always

# - name: Delete wireshark installation
#   import_playbook: ../static-assignments/common-del.yml

# - name: Webserver assigments
#   import_playbook: ../static-assignments/uat-webservers.yml

# - name: Loadbalancers assignment
#   import_playbook: ../static-assignments/loadbalancers.yml
#   when: load_balancer_is_required

# - hosts: db
# - name: database assignment
#   import_playbook: ../static-assignments/database.yml

# - hosts: nginx
# - name: nginx assignment
#   import_playbook: ../static-assignments/nginx.yml

# - hosts: artifactory
# - name: artifactory assignment
#   import_playbook: ../static-assignments/artifactory.yml

# - hosts: todo
# - name: deploy todo assignment
#   import_playbook: ../static-assignments/deployment.yml

- hosts: sonarqube
- name: sonarqube assignment
  import_playbook: ../static-assignments/sonar.yml